name: CI/CD TEST Pipeline
run-name: CI/CD Pipeline - by  @${{ github.actor }}
on:
  push:
    branches: ["dev"]
    paths: 
      - '**/*.py'
      - 'requirements.txt'
      - '.github/workflows/**'
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        # env:
        #   LOGISTIC_MODEL: ${{ secrets.LOGISTIC_MODEL }}
        #   RF_MODEL: ${{ secrets.RF_MODEL }}
        run: pytest
