name: Show GitHub Secret

on:
  workflow_dispatch:

jobs:
  extract-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret (unsafe demo)
        run: |
          echo "Extracting GitHub Secret..."
          echo "SECRET VALUE: $MY_SECRET"
        env:
          MY_SECRET: ${{ secrets.API_KEY }}